### PR TITLE
Hu9o patch 3

### PR DESCRIPTION
**Pull request by hu9o**
Add onDropFile (formerly onUpload).

The renaming of onUpload is a non-breaking change, since onUpload never worked anyway. Other props would benefit from a rename, but it's not probably worth introducing a breaking change.

### CODE REVIEW

**Comment by hu9o** [comment]
This pull request is only supposed to contain one commit (c5766ee).
I must have mixed up things in git, don't know how to fix this... any help?

**Comment by kokarn** [comment]
Even only that commit contains some breaking changes in the doc. 
```onLoadFailure``` and ```onLoadSuccess``` are used in the example.

Easiest way probably is to just re-do the pull request with only the intended changes.

**Comment by mosch** [comment]
Looks good anyway. You could [squash your commit](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit). 

But i think this is a breaking change. It's better to mark it so, because increasing the major version has no disadvantages.

**Comment by hu9o** [comment]
@kokarn You're right, that was a mistake. I intended to use ``onImageLoad`` and ``onLoadFailed``.
@mosch If you want to increase major version, what about renaming ``onImageLoad`` and ``onLoadFailed`` to ``onLoadSuccess`` and ``onLoadFailure`` ? The current names aren't very consistent, and this new naming would highlight they symmetry/related-ness and describe better their behaviour IMO.

**Comment by mosch** [comment]
@hu9o agree! `onLoadSuccess` and `onLoadFailure` are way better. feel free to change them right away, i'll be pleased to merge it.

**Comment by hu9o** [comment]
Here it is: https://github.com/mosch/react-avatar-editor/pull/65

**Pull request closed without merging**
