### PR TITLE
Adds ability to disable drop handling behavior

### PR DESCRIPTION
**Pull request by oyeanuj**
Hi @mosch, 

This PR allows toggling off the drop behavior. For my usecase, the parent element was already handling drop behavior and I was looking to pass the file directly into the editor. I'll have another PR soon on that functionality.

Thanks!

### CODE REVIEW

**Comment by mosch** [comment]
Hey @oyeanuj thanks for your contribution. I recently ran into the same problem when I was using this in a project.
I'll like to merge this, however I also thinking about removing this from the library completely since there are awesome libs that do the same job.
Or maybe exporting the Drop module for BC, like so 

`import AvatarEditor, { Dropable } from 'react-avatar-editor' 
<Dropable …>
  <AvatarEditor />
</Dropable>
`

let me know what you think.

**Comment by mtlewis** [comment]
One option is to use a capturing event listener in your wrapping drop some component - that way the avatar editor never sees the drop event. +1 for removing drag drop functionality - seems better to me to simplify this component and let something else handle the drag & drop stuff.

**Comment by oyeanuj** [comment]
@mosch @mtlewis good points. if you'd like to go in that direction (remove drop functionality), here is what I was thinking. 

I was thinking something along the similar lines but with the flexibility of using another library. In my case, I already am using [`React-Dropzone`](https://github.com/okonet/react-dropzone) (seems the most common) in my code elsewhere. Plus, it allows you to focus on maintaining `AvatarEditor` on just that and let people choose the `drop` library that they prefer (which usually focus on that one thing).

I think we'll need the following changes to make this happen - 
1. For the parent to be able to pass in an image of type `File` or `Blob`. Currently, it is restricted to a url.
2. To offer a `placeholder` component, until the image is loaded. Just a prop that user can fill with a function or a component?
3. An example which shows this in action, so that users who upgrade can have the same experience as before.

What better time for a breaking change than v10 😄

**Comment by mtlewis** [comment]
Strongly agree that there should be a helpful example of integration with a drag-drop solution. 

Regarding File support - I don't believe this is actually necessary, as you can simply convert your file to a data URI and pass it in. 

Is the placeholder not another candidate for functionality that can be kept external? Simply render your placeholder component instead of the AvatarEditor whenever it makes sense to do so.

**Comment by oyeanuj** [comment]
@mtlewis Good points, those changes aren't needed then.

**Comment by mtlewis** [comment]
Thinking about this more, it does seem friendlier to allow users to pass Files to the component, rather than only accepting URLs. @mosch, what are your thoughts? I'm happy to work on this - unless you've started on it already @oyeanuj?

**Comment by oyeanuj** [comment]
@mtlewis I haven't started yet, all yours!

**Comment by mtlewis** [comment]
All done - #189.

**Comment by oyeanuj** [comment]
@mtlewis @mosch Are you guys leaning towards removing the option completely or merging the above PR?

**Comment by mtlewis** [comment]
+1 for removing.  Better to make the component simpler than more complicated :)

**Comment by mosch** [comment]
@oyeanuj removing it. there are components that focus only on drag and drop. we should use them instead. however i would like to provide a simple drag and drop component for backwards compatibility.

**Comment by oyeanuj** [comment]
@mosch Let me know if we can merge this PR until you have the chance to remove the drop functionality? I imagine it would be a major version bump, so maybe until then, this PR could be useful?

_Either way, I've updated it to have all the latest changes from master_

**Comment by mosch** [comment]
great, let's merge it to a feature version, and then remove it later.

**Pull request merged**
