### PR TITLE
Support x and y borders

### LINKED ISSUE #140: Ability to have different borders
Would be awesome if we could specify different borders so that we could emulate what facebook does (no top and bottom border, but left and right border)

### PR DESCRIPTION
**Pull request by sktt**
Hi there!

Thanks for a great react component. I had a use case where I needed different x and y borders to allow selecting between different aspect ratios.  

Would you be interested in this too?

Fixes #140 and possibly #79

### CODE REVIEW

**Comment by sktt** [comment]
Wow this was already requested in #140

**Comment by mosch** [comment]
hey @sktt are you willing to resolve these conflicts? i would love to merge this pr 😇

**Comment by sktt** [comment]
hey @mosch! I rebased but something broke?

**Comment by mosch** [comment]
ah it looks like a other merge screwed up the linting, let's fix that first

**Comment by sktt** [comment]
@mosch done!

**Comment by mosch** [comment]
awesome, thanks! 🎉

**Pull request merged**
