### PR TITLE
Fix for bounds issue introduced from last pull request that fixed #7

### LINKED ISSUE #7: Is `calculatePosition` giving out the right x and y?
I'm running issues with images being rendered out of bound on the y-axis - the image's y origin will be at the bottom border (max y).

After some tracing I think `calculatePosition` function may be the one that causing the issue. However, since I couldn't figure out what is the intend of the original code, I figured it is better to open an issue instead of the pull request.

I did this change:

```diff
diff --git a/index.js b/index.js
index d75e0e2..3ad6739 100644
--- a/index.js
+++ b/index.js
@@ -120,8 +120,8 @@
                 var lastX = this.state.image.x;
                 var lastY = this.state.image.y;
 
-                var x = Math.round((width  + lastX <= borderX) ? lastX + (borderX - (width  + lastX)) : lastX);
-                var y = Math.round((height + lastY <= borderY) ? lastY + (borderY - (height + lastY)) : lastY);
+                var x = Math.round((height + lastX <= borderX) ? lastX + (borderX - (height + lastX)) : lastX);
+                var y = Math.round((width  + lastY <= borderY) ? lastY + (borderY - (width  + lastY)) : lastY);
 
                 return {
                     x: x,
```

and for my use case this did resolve the bug I saw.

I found it strange that while `borderX` is calculated based on `dimensions.height`, here calculating `x` was done with `width`, instead of `height`.

### PR DESCRIPTION
**Pull request by codedmart**
@mosch This should solve the last bug re introduced from my last pull request. I still have a bounds issue when try to get to the drag all the way to the bottom of an image, but it seems like I had that problem before any of my pr's. It might depend on the image as well. I will need to check. Thanks!

### CODE REVIEW

**Comment by codedmart** [comment]
@mosch Any word on this one, Thanks!

**Comment by mosch** [comment]
@codedmart i'm currently trying to find a solid way to do this. 
the current version is broken if you scale and drag the image. i'm now trying to fix all the issues at once.

**Comment by codedmart** [comment]
@mosch OK, this seems to work well for me when I scale and drag. I don't have any issues with it right now, but fair enough.

**Comment by mosch** [comment]
ok. can you give me your test image? i'm testing with a horizontal image …

**Comment by codedmart** [comment]
@mosch OK sorry I was wrong. There was a problem with y bounds, but I can't remember if I had that problem before any of my pr's or not. I know I had that problem before this pr. Anyhow try with the latest changes to this pr. All seems to be working well for me now.

**Comment by codedmart** [comment]
@mosch this works great for me now.

**Comment by mosch** [comment]
@codedmart will check it out today, thanks. i'm quite busy right now - so sorry for the delay

**Comment by codedmart** [comment]
@mosch No worries just making sure.

**Comment by mosch** [comment]
If you drag the image quite fast, it will "jump" out of the cropping frame. It think all the problems are related to how and when we do the calculations. I want to make some research and see if there is a better way to do this. Maybe s.th. very different. Any ideas?

**Comment by codedmart** [comment]
@mosch I agree there are still issues. I have not put in a lot of time to all the calculations, but I still think with this PR things are better then the current package on npm. At least for me. So my feedback would be merge and release with this while you / I / anyone else comes up with a more solid solution.

**Pull request merged**
