### PR TITLE
Upgrading babel and rollup to latest

### PR DESCRIPTION
**Pull request by TheMcMurder**
Fix an issue created by using an old version of rollup.

Some projects assume that their dependencies have the full object prototype available to them. This throws an error when the dependency does not have the Object.Prototype methods on it. In our case this occurs with React when in the bundled code the following happens:

`React = React && React.hasOwnProperty('default') ? React['default'] : React`

This issue hasn't cropped up as of yet because most people aren't using ES Modules and this bug really only affects ES_Modules or formats that emulate them (like System.register) and ES Modules _must not_ have `Object.prototype` as their prototype (it is expressly forbidden) so the erroneous assumption that rollup made in old versions is that external dependencies (in this case react) had the object prototype necessary to call `hasOwnProperty` but anyone using this library and ES (or System.register) modules is guaranteed to have an error because of the specification.

Upgrading `Rollup` is all that necessary to fix this issue but I thought it would be helpful to also upgrade `babel` for you.

Unfortunately there is an issue with the netlify build that makes it appear as though this build is failing when in reality we just need to upgrade to a more modern version of node on the netlify server. The current version that this build is running on (v6) was marked end of life in April of 2019 so we're well past the end of life date.  I suggest an upgrade to v10 or v12 (LTS) both of which are supported until April 2021 and April 2022 respectively.
 
References:
https://github.com/systemjs/systemjs/issues/2147
https://github.com/rollup/rollup/pull/3420
https://github.com/tannerlinsley/react-table/issues/1995

### CODE REVIEW

**Comment by TheMcMurder** [comment]
Additionally netlify will need to be upgraded to use a newer version of node

Currently it's on `node v6.17.1` it would be a good idea to move that to a recent LTS release

**Comment by TheMcMurder** [comment]
@mosch Due to the netlify node version the build is using this fails deployment despite passing all tests. What would it take to get this merged and published to NPM?

**Comment by TheMcMurder** [comment]
@mosch Is there anything I can do to help get this fix merged?

**Comment by mosch** [comment]
@TheMcMurder I'll check it out tonight!

**Comment by mosch** [comment]
Published as v11.0.10

**Comment by mosch** [comment]
@TheMcMurder https://github.com/mosch/react-avatar-editor/issues/340 this seems to issued a new problem

**Pull request merged**
