### PR TITLE
Small improvements and fixes

### PR DESCRIPTION
**Pull request by nmn**
In this pull request:
- A better test for touch support that doesn't explode on the server-side
- added options to set the type and quality when getting the data url from the canvas

also:
- patch version bump (since it is still 0.x.y, I would suggest releasing 1.0.0 and following semVer)
- remove reactify transform (the code doesn't need it)
- add peerDependency on React (it is needed to work)

### CODE REVIEW

**Comment by mosch** [comment]
lovely :heart: thank you!

**Comment by nmn** [comment]
please ping me when you release this on npm. I'm using my fork in production.

**Comment by mosch** [comment]
@nmn version 1.0.0 on npm ;)

**Comment by nmn** [comment]
Thanks. I'm using it for upclose.me in production.

**Comment by mosch** [comment]
thanks, i'm happy to see it's useful for others. 
I also see that it doens't work perfekt in terms of usability. Let's try to improve it further ;)

**Comment by nmn** [comment]
I've been suer busy of late. Otherwise, I plan to add pinch-to-zoom support someday.

**Pull request merged**
