### PR TITLE
Add ability to set x and y from props

### PR DESCRIPTION
**Pull request by raigfp**

### CODE REVIEW

**Comment by mosch** [comment]
Hi @raigfp, thanks for your PR! Is this about the initial X and Y for the passed image? Than i would go for "The initial y/x position" in the docs. 
Im also interested what you like to achieve with this, what do you need it for?

**Comment by raigfp** [comment]
Hello! Yes, it's exactly about it.
In my project I need to load crop position from server (result of my last crop) to continue cropping

**Comment by mosch** [comment]
Spotted a problem: If you upload a new image, the x and y will not be resettet

**Comment by pfrend** [comment]
created an issue for this https://github.com/mosch/react-avatar-editor/issues/108. We really need this feature as well. Might have some time to look at it next week. @raigfp are you still planning on working on this?

**Comment by hu9o** [comment]
I think there is a convention in React component, by which _"initial props"_—that is, props whose value is only used to initialize the component—are prefixed with "initial".

Though I'm not sure how widespread this convention is, I find that it is helpful to differentiate between _initial_ props and normal ones, because of their quite distinct behaviours.

Perhaps ``initialX`` and ``initialY`` (or ``initialXOffset`` and ``initialYOffset``) would be more evocative prop names.

**Comment by Dictory** [comment]
@mosch, hi. I think it is nice feature. User can just reset x and y after success upload image in parent component

**Pull request merged**
