### PR TITLE
Add support for passing File in image prop

### PR DESCRIPTION
**Pull request by mtlewis**
* `image` prop can now contain a `File` or string.
* Add information about `image` prop to README (and a little bit of general cleanup of the props table).
* Add file chooser to demo to make it easy to test this functionality.

### CODE REVIEW

**Comment by oyeanuj** [comment]
@mtlewis This is awesome! One small suggestion since you are cleaning up the props table is adding a column for default values?

**Comment by mtlewis** [comment]
Thanks @oyeanuj :) 

Sounds like a good idea to me, but as I'm short of time for the rest of the weekend perhaps we should keep it as a separate task.

**Comment by mosch** [comment]
this is awesome and a good step towards the drop thing discussed in here https://github.com/mosch/react-avatar-editor/pull/184

**Comment by dan-lee** [comment]
@mtlewis Fantastic, thank you!

**Pull request merged**
