### PR TITLE
Add function to rotate the image by 90/180/270 degres

### PR DESCRIPTION
**Pull request by MykolaPrymak**
Add function rotate, who accept the angle in deg.

Function not have a memory and always rotate again if called twice. So
rotate(90);
rotate(90);

will rotate image to 180 deg.

### CODE REVIEW

**Comment by mosch** [comment]
I like the idea of adding this. I see this like the scale, so this should get passed in as prop

**Comment by mosch** [comment]
@MykolaPrymak any thoughts about adding this as a prop to the editor?

**Comment by MykolaPrymak** [comment]
Little busy right now.

**Comment by MykolaPrymak** [comment]
I update the rotation functionality. Now it can be used with props.

**Comment by hu9o** [comment]
It seems like the rotation is not applied again on image load, resulting in a non-rotated image even though the ``rotation`` prop is potentially different from zero.

While easy to fix, this issue makes me wonder whether keeping state for rotation is the way to go. The alternative would be to apply the rotation (passed via props) at each draw. We would have to take this into account in the computations involving the image's dimensions (inverted width/height if rotation is 90 or 270 deg), which may be cumbersome.

**Comment by davidholland** [comment]
Can we possibly get this soon?  We are using this utility but are considering switching since the rotate feature is missing.

**Comment by onzag** [comment]
D:

**Comment by mattcolman** [comment]
Do ppl want to add the rotate function because of EXIF orientation from phones? If so, we would also need to add FLIP. 
Maybe this is a separate issue, I think we should look into handling EXIF orientation regardless. 
I might look into this unless someone else already has...?

**Comment by mosch** [comment]
@mattcolman that would be great. we'll need something like this too. so i'm open to assist you on this.

**Comment by mosch** [comment]
I close this for now. I think this feature is really cool. Let's reopen it if s.o. finds the time to get it right.

**Comment by MykolaPrymak** [comment]
OK.

2016-10-26 10:21 GMT+03:00 Moritz Schwörer <notifications@github.com>:

**Comment by kevinmcalear** [comment]
I would still love to see this implemented.

**Pull request closed without merging**
