### PR TITLE
remove crossOrigin from image in loadImage if isDataURL

### PR DESCRIPTION
**Pull request by codedmart**
@mosch if crossorigin is set on the resulting img when the src is a dataURL firefox fails silently to load the image properly. This fixes that. Thanks!

### CODE REVIEW

**Comment by mosch** [comment]
@codedmart thanks for your contribution! i was on vacation - i'll look at this in details tomorrow.

**Comment by mosch** [comment]
thanks :+1:

**Comment by codedmart** [comment]
@mosch does this one look ok and make sense to you? I am working with dataURL's and ran into this problem.

**Comment by codedmart** [comment]
@mosch I could fix it so there are no merge conflicts if you want.

**Comment by mosch** [comment]
i merged it manually. this one can be closed.

**Pull request closed without merging**
