### PR TITLE
center image, fixes #2

### LINKED ISSUE #2: Keep image centered while scaling

### PR DESCRIPTION
**Pull request by bluej100**

### CODE REVIEW

**Comment by bluej100** [comment]
Ping. If you would like me to break this into simpler commits or something, I'd be happy to.

**Comment by mosch** [comment]
Sorry for the delay. It might help me if you describe what you changed to achieve this. I'll check this out and test it today.

**Comment by bluej100** [comment]
There are basically two changes. The simpler change is adding a border parameter to paintImage and calculatePosition so it doesn't have to be included in the image properties. The larger change is that image.x and image.y now refer not to the position of the top-left corner of the image but to the position of center of the "camera" on the original image. That way when scale changes, the center of the crop does not. This is why xDiff and yDiff are now divided by scale: you move the selection more slowly at higher zoom.

**Comment by mosch** [comment]
wow this is great and makes things even simpler…

**Comment by bluej100** [comment]
Thank you! :grinning: I was happy that I was able to simplify some things, yes.

**Comment by bluej100** [comment]
Would you mind releasing a new version when convenient for you?

**Comment by mosch** [comment]
Working on it right now :)

**Comment by bluej100** [comment]
Thanks a bunch. I like the downloads badge. :)

**Pull request merged**
