### PR TITLE
Add a high quality boolean flag

### PR DESCRIPTION
**Pull request by bluej100**
Rebase of https://github.com/mosch/react-avatar-editor/pull/45 .

### CODE REVIEW

**Comment by cptroot** [comment]
Thanks so much for doing this. I'm closing #45 in favor of this pull request.

**Comment by bluej100** [comment]
My pleasure. Thanks for your original work.

**Comment by bluej100** [comment]
@mosch , was this closed because you don't think it's useful or just because it developed a merge conflict?

**Comment by mosch** [comment]
@bluej100 sorry but i really don't remember why i closed this. 
i think this is a really good one! but i also think we should change a few things.
 - Since "highQuality" is a good thing, it should be the default behaviour
 - The highQuality "flag" should be not a property of the component but an *argument* of the *getImage()* function 
- I don't see too much of the same code in *paintImage()* and *getImage()*, so i think it's better do everything in the *getImage()* method instead of calling *paintImage()

What do you guys think?

**Comment by hu9o** [comment]
My humble opinion on this :

I agree wholeheartedly on the first two bullet-points.

To me, the name ``highQuality`` does not fit perfectly the idea of keeping the size untouched, especially considering that the output quality will be poor anyway if so is the input image's. I would prefer something along the lines of ``realSize``/``fullSize``/``noResize``.

What about two optional last parameters to ``getImage()``, being the width and height of the image to return? That would allow to get "low quality" by passing the editor's width/height, "high quality" by not passing any width/height, or any other size one might want.

**Comment by mosch** [comment]
Jip, I think adding two optional paramters to `getImage()` is the right approach. This gives maximal flexibility!

**Comment by chengyin** [comment]
In my opinion the editor should always provide the image with the minimal manipulation.

The focus of this lib is cropping. If resize is needed, let it be some other lib's job. The developer can always funnel the un-resized image into something else for resizing. We don't need to complicate this project with extra options.

**Comment by chengyin** [comment]
I built my own version: https://github.com/mosch/react-avatar-editor/compare/master...Backplane:master

I am more extreme here and I understand the desire for having no breaking changes like this. I do think it would be easy to implement an options if needed.

**Comment by mosch** [comment]
@chengyin i strongly agree with your arguments. I want to keep this thing simple and clean.
I think it's a good thing to not resize the image because it limits the usage of this thing as we can see.

I would appreciate a pull request of your version!

**Comment by dtryon** [comment]
+1
I like the suggestion for this to be controlled through parameters on `getImage()`.  Are we likely to see a merge soon?

**Comment by rkuykendall** [comment]
@mosch @chengyin I would really love to get original-resolution images from this component. It looks like a lot of solid work has already been done here. Is there anything I can do to get this PR rolling?

If you're both busy maybe I can try to re-create @chengyin's changes in a fork off the current master?

**Comment by hu9o** [comment]
I rewrote ``getImage`` so it returns the cropped image in the original resolution.
Please note that I haven't tested it yet :

    getImage: function getImage(type, quality) {
        // get relative coordinates (0 to 1)
        var cropRect = this.getCroppingRect();
    
        // get actual pixel coordinates
        cropRect.x      *= image.resource.width;
        cropRect.y      *= image.resource.height;
        cropRect.width  *= image.resource.width;
        cropRect.height *= image.resource.height;
    
        // create a canvas with the correct dimensions
        var canvas = document.createElement('canvas'); 
        canvas.width  = cropRect.width;
        canvas.height = cropRect.height;
    
        // draw the full-size image at the correct position,
        // the image gets truncated to the size of the canvas.
        canvas.getContext('2d').drawImage(image.resource, -cropRect.x, -cropRect.y);
    
        return canvas.toDataURL(type, quality);
    }

Besides, I really think ``getImage`` should simply take no parameter and return a canvas.

**Comment by rkuykendall** [comment]
I successfully switched to using https://github.com/Backplane/react-avatar-editor/

Obviously that's just a band-aid, but it's working for now, and hopefully something similar makes it into the main repo soon.

**Comment by hu9o** [comment]
Ok, anyway, I tested my function :
Except for the fact that I forgot to define `var image = this.props.image`, it works as intended.
I'll make a PR soon.

**Comment by mosch** [comment]
imho fixed by #98 and #97

**Pull request closed without merging**
