### PR TITLE
Add support for rotation

### PR DESCRIPTION
**Pull request by kuka**
Works with dropped images and keeps rotation angle intact with both landscape and portrait modes.

### CODE REVIEW

**Comment by kuka** [comment]
@mosch Could we incorporate this PR? Pretty straightforward changes.

**Comment by mosch** [comment]
so cool! 🎉

**Comment by dan-lee** [comment]
@kuka Why did you re-add the `dist` folder? This should rather not be inside the repository.

**Comment by kuka** [comment]
@dan-lee Yeah, you’re totally right! Installation was not working for me in my repo as dist wasn’t there. This got incorporated into PR. Now that it’s merged, `prepublish` should work alright for npm version. I’ll make a PR with cleaned dist and updates towards README.

**Pull request merged**
