### PR TITLE
Fix disableCanvasRotation prop psssing to canvas DOM element

### LINKED ISSUE #347: 11.0.11 React does not recognize the `disableCanvasRotation` prop on a DOM element
```
Warning: React does not recognize the `disableCanvasRotation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disablecanvasrotation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

https://github.com/mosch/react-avatar-editor/blob/44e79535f7125ccd389e9d5d9077bccc1f14d969/src/index.js#L731

### PR DESCRIPTION
**Pull request by kuhelbeher**
Fixes #347

### CODE REVIEW

**Comment by ab1303** [comment]
Hi,
  Still getting this error, Is there going to be a release soon with this fix please ?
Thanks

**Comment by MrPurpose** [comment]
> Hi,
> Still getting this error, Is there going to be a release soon with this fix please ?
> Thanks

Same here

**Comment by kuhelbeher** [comment]
Because it's not published yet.

@mosch could you please publish new version with this fix?

**Comment by paulohgontijoo** [comment]
Hi guys, i'm having the same issue on my aplications. Nice to see that someone has provided the solution!! @mosch could you publish the new version for the community? Thank you!!

**Comment by dan-lee** [comment]
I just released v11.0.13, hope it works for you now.

**Pull request merged**
