### PR TITLE
fixes disableBoundaryChecks warning

### PR DESCRIPTION
**Pull request by omnisyle**
Remove disableBoundaryChecks in default props since it'll be falsy by default

### CODE REVIEW

**Comment by selaux** [comment]
This also an issue for us. I would put it into the destructuring [here](https://github.com/mosch/react-avatar-editor/blob/master/src/index.js#L648) instead, so `disableBoundaryChecks` is not set on the `canvas` element, even if it is set on the `ReactAvatarEditor` component.

**Comment by DenizTemizer** [comment]
I would stick with @selaux answer. Removing disabledBoundaryChecks from defaultProps would make it undefined and not false.

**Comment by mosch** [comment]
I agree, let's put it in the destructuring to get rid of it.

**Comment by omnisyle** [comment]
@mosch I updated my commit to get rid of disableBoundaryChecks by destructuring

**Comment by mosch** [comment]
thanks!

**Comment by zslabs** [comment]
👋 Any chance of a formal release with this fix?

**Comment by mosch** [comment]
done

**Pull request merged**
