### PR TITLE
Tiny improvement: Cursor changes to a hand when over the component

### PR DESCRIPTION
**Pull request by hu9o**
Set default CSS 'cursor' property to 'grab' when hovering over, and to
'grabbing' dragging around.
(see index.js)

### CODE REVIEW

**Comment by hu9o** [comment]
Lets the user know they can drag the image around, better UX I guess.

**Comment by mosch** [comment]
cool, thanks!

**Comment by hu9o** [comment]
👍

**Comment by dbismut** [comment]
`grab` property is not supported by Chrome. `move` should be though.

**Pull request merged**
