### PR TITLE
getImage() returns image in original resolution

### PR DESCRIPTION
**Pull request by hu9o**
That is, without zoom, as suggested in #54.

### CODE REVIEW

**Comment by mosch** [comment]
this looks great!

**Comment by hu9o** [comment]
Thanks.

By the way, you'll probably notice that ``getCroppingRect()`` gives coordinates relative to size, like this :

```javascript
return {
    x: (frameRect.x - imageRect.x) / imageRect.width,
    y: (frameRect.y - imageRect.y) / imageRect.height,
    width: frameRect.width / imageRect.width,
    height: frameRect.height / imageRect.height,
};
```

So ``getImage()`` has to do the following on ``getCroppingRect()``'s return :

```javascript
    // get actual pixel coordinates
    cropRect.x      *= image.resource.width;
    cropRect.y      *= image.resource.height;
    cropRect.width  *= image.resource.width;
    cropRect.height *= image.resource.height;
```

It looks a bit convoluted...
Conversely, we don't really need another function to get the cropping rect in pixels.
I say we simply provide the cropping rect in pixels only.

**Comment by dan-lee** [comment]
This is good! But it will introduce a breaking change as it changes the outcome of the image as it was before.
We should increase the major version and provide a solution to scale the image as it was before.

**Comment by hu9o** [comment]
While we're making breaking changes : #98

**Comment by hu9o** [comment]
Sorry, can you reopen this PR ? I had forgotten to update README.md... (now done,on this branch)

**Comment by mosch** [comment]
not really. I can make a new PR that will revert your changes. Can you just add a new PR for the update of the readme? Would be great 🐐

**Pull request merged**
