### PR TITLE
Fix example with bad practice checking existence of ref

### PR DESCRIPTION
**Pull request by rhagigi**
React purposely passes null to ref functions when a component is unmounted so that you set whatever was referencing it to null, to ensure proper garbage collection. It's a bad idea to check the existence of the parameter before setting whatever you were gonna set -- you're *intended* to set it to null.

### CODE REVIEW

**Comment by hu9o** [comment]
The example script seems incorrect:
I haven't tested it, but there's no call to `onClickSave` and no _null-check_ inside it...

**Comment by rhagigi** [comment]
Good point @hu9o -- realistically there should be better examples throughout. I only brought this one up as it's something I noticed offhand.

**Comment by dan-lee** [comment]
I was not aware that this is bad practice. So basically there has to be check everytime the ref is used? Like `if (editor) doSomething(this.editor.getImage())`

**Comment by hu9o** [comment]
@dan-lee First thing, the removed check didn't prevent `this.editor` from being `undefined` (before the first call to `setEditorRef()`). More importantly, React calls `setEditorRef()` with `null` to invalidate the previous ref, so we better **not** keep it anyway.

So yes, we have to null-check prior to any use — unless we call it from `componentDidMount()` or `componentDidUpdate()`.

**Comment by mosch** [comment]
this was solved somewhere else.

**Pull request closed without merging**
