### PR TITLE
Add a high quality boolean flag

### PR DESCRIPTION
**Pull request by cptroot**
These commits add a `highQuality` boolean flag to allow users of this plugin to request native resolution croppings of the original images, as opposed to component-sized croppings.

### CODE REVIEW

**Comment by bluej100** [comment]
Looks good!

I believe that index.es5.js is a generated file, so I think these changes should be in index.js. I've done so on a squashed branch at https://github.com/bluej100/react-avatar-editor/tree/highQuality . I can submit a pull request for it if you like.

**Comment by cptroot** [comment]
@bluej100 That looks great. Do you know if both files should be modified or just the index.js?

**Comment by bluej100** [comment]
Oh yeah, good catch. Thanks. I've done so at https://github.com/mosch/react-avatar-editor/issues/54 .

**Comment by bluej100** [comment]
By the way, I also modified example/app.js to include a highQuality checkbox.

**Comment by cptroot** [comment]
Closing this pull request in favor of #54.

**Pull request closed without merging**
