### PR TITLE
make html5 canvas fill() using 'evenodd' explicitly - to fix safari i…

### PR DESCRIPTION
**Pull request by metacortex**
…ssue

### CODE REVIEW

**Comment by hu9o** [comment]
Thanks for the fix !

Is that a bug in Safari ? I can't find any relevant bug report besides https://code.google.com/p/chromium/issues/detail?id=51650, which reports the bug to be fixed in Safari.

**Comment by metacortex** [comment]
Yes. it should work.
but safari has problem using fill() with default value.

OSX - Safari Version 9.0.3 

It just fills entire area. not only border area.

you can check it.

**Comment by Persata** [comment]
We also experienced this issue with Safari on both iOS and OSX, and can confirm that this fixes the issue on both.

**Comment by mosch** [comment]
thanks.

**Pull request merged**
