### PR TITLE
allow control over how fast image drags

### PR DESCRIPTION
**Pull request by jakerichan**
Dragging the image feels sluggish for my application. Optional drag speed will help anybody customize this feature for their application.

### CODE REVIEW

**Comment by mosch** [comment]
Is the sluggish behaviour owing to this a performance problem? Because if so i would prefer to to fix the performance problems instead.

**Comment by jakerichan** [comment]
It's not really a performance issue. Line #234 is just limiting how much the image can move, even if the mouse is going faster.  Personally, I like it to almost be equal with the actual movement of my mouse, so I will crank it up to a max of up to 50px in any direction.  

i.e. With a low setting, if I want to move my crop area to the other side of a zoomed image it takes a few passes.  I like being able to get to either side of the image in a single pass.

**Comment by mosch** [comment]
I just tried to not limit the dragging speed at all by removing the max/min calculation lines.
I think i did this to limit the overdrag you just fixed in you PR. Can you try how it feel in you app when you remove the lines? I would love to kick them out :-)

**Comment by jakerichan** [comment]
Fantastisch! Ich sehe du wohnst aus Freiburg, also kann Ich Deutsch sprechen. Stimmt?

**Comment by mosch** [comment]
Ja, ich spreche auch Deutsch :-) Kennst du Freiburg? Oder bin ich durch mein Englisch aufgefallen?

**Comment by jakerichan** [comment]
Ich kenne Freiburg. Wir reisen auf Deutschland in Mai und wir denken Freiburg zu besuchen. Kennst du Sehenswürdigkeiten zu sehen?  Dein Englisch ist sehr gut, Ich habe das auf deine Profil gelesen.  Du kannst mir mailen an jake.richan@gmail wenn du möchte.

**Pull request merged**
